[package]
name = "nix-shell-locked"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
exec = "0.3"
log = "0.4"
meap = "0.7"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
shellexpand = "3.1"
toml = "0.7"
xdg = "2.5"
